Opti-mat/optiMat/__init__.py
from flask import Flask 
from optiMat.model import db
from flask_login import LoginManager
from flask_login import login_manager


login_manager = LoginManager()

# create OPTIMAT app
app = Flask(__name__, static_url_path='/static')
app.config["SECRET_KEY"] = 'material_selection_assistant77234'

# configure the SQLite database, relative to the app instance folder
app.config["SQLALCHEMY_DATABASE_URI"] = 'sqlite:///database.db'

    

# initialize the database to the app 
db.init_app(app)

# with app in context, create database 
with app.app_context():
    db.create_all()


# initialize logging in 
login_manager.init_app(app) 


@login_manager.user_loader
def load_user(user_id):
    from optiMat.model import User 
    return db.session.execute(db.select(User).filter_by(id=1)).scalar() #Load user from the database 

from . import routes
app.register_blueprint(routes.bp)
   
if __name__ == "__main__":
    app.run(debug=True)
    
        

Opti-mat/optiMat/routes.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, flash
)
from flask_login import login_user, logout_user, login_required
from werkzeug.exceptions import abort
from .assistant import AssistantManager
import json
from optiMat.authentication import SignupForm, LoginForm
from optiMat.model import db, User 

bp = Blueprint('routes', __name__)

#route for Homepage
@bp.route('/')
@bp.route('/home')
def index():
    return render_template('index.html')


#Route for signup
@bp.route('/signup', methods= ['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash('Email address already registered', 'Error')
        else:
            new_user = User(email=form.email.data)
            new_user.set_password(form.password.data)  # Hash password before saving
            db.session.add(new_user)
            db.session.commit()
            flash('You have successfully signed up!', 'success')
            return redirect(url_for('routes.form'))
    return render_template('signup.html', form=form)

# route for login
@bp.route('/login', methods= ['GET', 'POST'])
def login():
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.check_password(form.password.data): # validate password 
            login_user(user)
            flash('You have succesffully logged in!', 'Success')
            return redirect(url_for('routes.form'))
    return render_template('login.html', form=form)

# route for logout 
@bp.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out', 'success')
    return redirect(url_for('routes.index'))


#route for form page 
@bp.route('/form', methods=('GET', 'POST'))
def form():
    return render_template('form.html')

# route for response page 
@bp.route('/response', methods =('GET', 'POST'))
def process():
    if request.method == 'GET':
        print('not allowed')
        return 'method not allowed'
    about: str = request.form.get('about')
    function: str = request.form.get('function')
    cost_constraint: str = request.form.get('cost_constraint')
    
    content = {
        "about": about,
        "function": function,
        "cost_constraint": cost_constraint,
    }

    content = str(content)
    meta_data = 'Recommend only one material and please leave your answer in the following json format.  { title: string (e.g Optimal material for fingerprint replacement), material: string (e.g. Acrylic), reason: string (e.g acrylic is highly biocamptible and as tough as fingerprints), key_properties: array of string(not more than 5) }'
    
    api_prompt = content + '\n' + meta_data
    
    manager = AssistantManager()
    manager.create_assistant()
    manager.create_thread()
    manager.add_message_to_thread(role='user', content=api_prompt)
    manager.run_assistant()
    response = manager.wait_for_completion()
    response = json.loads(response)
    
    keys = list(response.keys())
    isPresent = (('material' in keys) and ('title' in keys) and ('reason' in keys) and ('key_properties' in keys))
    print(isPresent)
    
    if len(keys) == 1:
        response = response[keys[0]]
    
    if isPresent:
        print('in here')
        return render_template('response.html', title = response['title'], material=response['material'], reason=response['reason'], key_properties = response['key_properties'])
        

    return render_template('response.html', title='hello', material='helloo', reason='hellooo', key_properties=['helloooooo']) # render_template('error.html')


Opti-mat/optiMat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css"href="{{url_for('static', filename='css/style.css')}}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-md sticky-top">
        <a class="navbar-brand" href="#">OPTI-MAT</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navb" class="navbar-collapse collapse hide">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home</a>
            </li>
          </ul>
      
          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#"><span class="fas fa-user"></span> Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"><span class="fas fa-sign-in-alt"></span> Login</a>
            </li>
          </ul>
        </div>
      </nav>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Opti-mat/optiMat/templates/error.html
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='errorStyle.css') }}"
/>

<div class="container">
  <span class="error"> hello error </span>
</div>

Opti-mat/optiMat/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Form | AI Material Selection Assistant</title>
  <link rel="stylesheet" href="{{ url_for('static', filename= 'css/formStyle.css')}}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
  <nav class="navbar navbar-expand-md sticky-top">
    <a class="navbar-brand" href="{{url_for('routes.index')}}">OPTI-MAT</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navb" class="navbar-collapse collapse hide">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('routes.index')}}">Home</a>
        </li>
      </ul>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.logout')}}"><span class="fas fa-user"></span>Log Out</a>
        </li>
      </ul>
    </div>
  </nav>

  <div id="questionnaire">
    <div class="title">
      <header>OPTI-MAT</header>
      <p>Your Material Selection Assistant</p>
    </div>
    
    <form id="questionsForm" action="/response" method="post">
      <div class="question-container" id="1">
        <label for="questionItem">1. What project are you working on today</label>
        <input type="text" name="about" class="form-control" required />
      </div>
      <div class="question-container" id="2">
        <label for="questionItem">2. What do you want your material to do functionally?</label>
        <input type="text" name="function" class="form-control" required />
      </div>
      <div class="question-container">
        <label for="questionItem">3. What's your cost constraint in this project?</label>
        <input type="text" name="cost_constraint" class="form-control" required />
      </div>

      <div class="button-submit">
        <button type="submit" class="register-button">Submit</button>
      </div>
    </form>
  </div>
  <script src="{{ url_for('static', filename='form.js') }}"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


</body>
</html>

Opti-mat/optiMat/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | AI Material Selection Assistant</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css"href="{{url_for('static', filename='css/indexStyle.css')}}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <!-- navigation bar  -->
    <nav class="navbar navbar-expand-md sticky-top">
      <a class="navbar-brand" href="{{url_for('routes.index')}}">OPTI-MAT</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navb" class="navbar-collapse collapse hide">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('routes.index')}}">Home</a>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('routes.signup')}}"><span class="fas fa-user"></span> Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('routes.login')}}"><span class="fas fa-sign-in-alt"></span> Login</a>
          </li>
        </ul>
      </div>
    </nav>


    <div class="hero-container">
      <div class="container">
        <header>Find the Best Material for your Design Project</header>
        <p>World's Best AI Material Selection Consultant</p>
        <button type="button" class="hero-button" data-mdb-ripple-init  onclick= "navigateToPage()">Try it now</button>
      </div>
      <div class="hero-image">
        <img src="{{url_for('static', filename = 'css/Search engines-bro.svg')}} " >
      </div>
    </div>
      
    <script>
      function navigateToPage(){
        // redirect to sign up page
        window.location.href = '/signup';
      }
    </script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Opti-mat/optiMat/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/loginStyle.css')}}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    <!-- receive alert messages on whether user is logged in -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="alert alert-info " role="alert">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}


    <div class="container">
        <div class="title">
            <header>Welcome! This is <span class="highlight">OPTI-MAT</span> </header> 
            <p>Your Material Selection Assistant.</p>
        </div>

        <form method="post" action="{{ url_for('routes.login') }}">
            {{ form.hidden_tag() }}
            <div class="mb-3">
             {{ form.email.label(class="form-label") }}
             {{ form.email( class= "form-control") }}
            </div>
            <div class="mb-3">
              {{ form.password.label(class="form-label") }}
              {{ form.password( class ="form-control") }}
            </div>
                {{form.submit(class= "register-button" )}}
          </form>
          
            <div class="signin">
             <span>Oops you don't have an account? <a href="{{url_for('routes.signup')}}">Sign up here</a></span>
            </div>
        </div>   
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

Opti-mat/optiMat/templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Response | AI Material Selection Assistant</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css"href="{{url_for('static', filename='css/responseStyle.css')}}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-md sticky-top">
    <a class="navbar-brand" href="{{url_for('routes.index')}}">OPTI-MAT</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navb" class="navbar-collapse collapse hide">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('routes.index')}}">Home</a>
        </li>
      </ul>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('routes.logout')}}"><span class="fas fa-user"></span> Log Out</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="response-container">


    <div class="response">
      <div class="title">{{ title }}</div>
      <div class="material">
        <span class="material-key">Material: </span>{{ material}}
      </div>
      <div class="reason">
        <div class="reason-key">Reason</div>
        <div class="reason-text">{{ reason }}</div>
      </div>
      <div class="key_properties">
        <div class="key_properties-key">Key Properties</div>
        <ul class="key-properties-text">
          {% for i in key_properties %}
          <li>{{ i }}</li>
          {% endfor %}
        </ul>
      </div>
      <div class="button">
        <a href="/form">
          <button>Ask New Question</button>
        </a>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Opti-mat/optiMat/templates/signup.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title> 
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/signupStyle.css')}}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<!-- receive alert messages on whether user is logged in -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="alert alert-info " role="alert">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <div class="container">
        <div class="title">
            <header>Welcome! This is <span class="highlight">OPTI-MAT</span> </header>
            <p>Your Material Selection Assistant.</p>
        </div>
        
        <form method="post">
            {{ form.hidden_tag() }}
            <div class="mb-3">
             {{ form.email.label(class="form-label") }}
             {{ form.email( class= "form-control") }}
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              {{ form.password.label(class="form-label") }}
              {{ form.password( class ="form-control") }}
            </div>
            <div class="mb-3">
                {{ form.confirm_password.label(class="form-label") }}
                {{ form.confirm_password( class ="form-control") }}
              </div>
                {{form.submit(class= "register-button" )}}
          </form>
            
            <div class="signin">
             <span>Already have an account? <a href="{{ url_for('routes.login')}}">Log in here</a></span>
            </div>
        </div>   
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</body>

</html>